source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
pod "AFNetworking", "~> 2.0"
pod "SVProgressHUD"
pod 'SDWebImage', '~>3.7'
pod 'NXOAuth2Client', '~> 1.2'
pod 'gtm-oauth2', '~> 1.0'